### ISSUE TITLE
New release with PR #30 included planned?

### ISSUE THREAD

**Issue by hafu** [linksmart-iosb/grafana-sensorthings-datasource#38]
The v1.3.0 is now about one year old. Is there any new release planned. The PR #30 which fixed #29 would help a lot.

https://github.com/linksmart/grafana-sensorthings-datasource/issues/29#issuecomment-673015239
> I will close this issue and draft a new release.

**Comment by farshidtz** [comment]
Hi,

We are facing some issues with the worldmap panel for location visualization. We working on fixing that before a release.

For now, please get the latest version from source:

* Clone the repository into Grafana's [plugin directory](http://docs.grafana.org/plugins/installation/#grafana-plugin-directory):
```
git clone https://github.com/linksmart/grafana-sensorthings-datasource.git linksmart-sensorthings-datasource
```
* Restart Grafana server to see the newly added datasource.

If using Grafana in a Docker container:
* Set environment variable:
```
GF_INSTALL_PLUGINS=https://github.com/linksmart/grafana-sensorthings-datasource/archive/master.zip;linksmart-sensorthings-datasource
```

**Comment by twei55** [comment]
@farshidtz I am facing issues when installing / downloading the plugin in a Docker container as described above. The url above redirects to `https://codeload.github.com/linksmart/grafana-sensorthings-datasource/zip/master` where the zip file can be downloaded, but AFAIK the plugin list expects a zip file extension at the end of the url.

**Comment by farshidtz** [comment]
@twei55 this is according to Grafana instructions available [here](https://grafana.com/docs/grafana/latest/installation/docker/#install-plugins-from-other-sources)

It works for me:
```bash
$ docker run -p 3000:3000 -e "GF_INSTALL_PLUGINS=https://github.com/linksmart/grafana-sensorthings-datasource/archive/master.zip;linksmart-sensorthings-datasource" --name grafana grafana/grafana
installing linksmart-sensorthings-datasource @ 
from: https://github.com/linksmart/grafana-sensorthings-datasource/archive/master.zip
into: /var/lib/grafana/plugins

✔ Installed linksmart-sensorthings-datasource successfully 
...
```

Docker compose:
```yaml
version: '2.2'
services:
    grafana:
        image: grafana/grafana
        environment:
            - GF_INSTALL_PLUGINS=https://github.com/linksmart/grafana-sensorthings-datasource/archive/master.zip;linksmart-sensorthings-datasource
        ports:
            - 3000:3000
```
